### ISSUE TITLE
In Example -> Provided cores: 1

### ISSUE THREAD

**Issue by wehrleju** [cbg-ethz/NGS-pipe#26]
Hey,

Thank you for developing that pipeline and providing it to the community.
I wanted to test your pipeline for my projects. 

When running the example data (RNA & WES) , the pipeline seems to be limited to one core:
```
$ ./run_analysis_locally.sh
Provided cores: 1
Rules claiming more threads will be scaled down.
```
I try to modify the the config.json file, but it seems that the configuration here would allow more cores.
Where should I adjust the config?

The machine  I am working on has 12 cores 64 GB of memory. - so this should not be the bottleneck. 

Thanks!
Sincerely 
Julius

**Comment by singerj** [comment]
Hi Julius,

just add -n <threads> to the snakemake command in /run_analysis_locally.sh .

Best,
Jochen

**Comment by singerj** [comment]
Hi again,

actually with -n you can restrict the number of threads used. However, you also need to specify -j to define how many jobs should be run at the same time.

Sorry for the confusion.

Best,
Jochen
