### ISSUE TITLE
 Warning : "Unable to set utime on symlink {}. Your Python build does not support it" 

### ISSUE THREAD

**Issue by AkankshaFarswan** [cbg-ethz/NGS-pipe#3]
When I run the file "run_prepare_data_locally.sh", it gives a warning "Unable to set utime on symlink {}. Your Python build does not support it" for the rule "Fastqs".

![screenshot](https://user-images.githubusercontent.com/29091911/31044163-cc2af308-a5e7-11e7-8984-73afcd9f1c08.png)

**Comment by singerj** [comment]
@AkankshaFarswan 

We fixed the problem according to http://snakemake.readthedocs.io/en/stable/project_info/faq.html?highlight=symlink#can-the-output-of-a-rule-be-a-symlink. Please do not hesitate to ask again if the problem remains.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
I used the updated code this time and it is again giving the error. I am
attaching the screenshot of the error.[image: Inline image 1]

Please help.

**Comment by singerj** [comment]
@AkankshaFarswan 

Hi, 

unfortunately I cannot see the screenshot you created. However, I downloaded the latest version and ran the script. During the last commit I accidentally introduced an error which I have now corrected. However, the linking issues is not resolved yet. As this is a know problem (http://snakemake.readthedocs.io/en/stable/project_info/faq.html?highlight=symlink#can-the-output-of-a-rule-be-a-symlink) and "only" a warning you can ignore the issue for the time being. I hope I can fix this problem soon.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
Hi,
Thank you for the help.
