### ISSUE TITLE
Error in "Qualimap" when running the file "**run_analysis_locally.sh**"

### ISSUE THREAD

**Issue by AkankshaFarswan** [cbg-ethz/NGS-pipe#4]
I am getting the following error when i try to run the "**run_analysis_locally.sh**".
I am attaching the screen shot of the error.
![screenshot-1](https://user-images.githubusercontent.com/29091911/31046352-87a35bc6-a614-11e7-8e75-74f9798a07aa.png)

**Comment by singerj** [comment]
@AkankshaFarswan 

Thank you for reporting this issue. We fixed it in the updated master branch.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
I just ran the file updated "run_analysis_locally". It is still giving me
the same error. Please help.[image: Inline image 1]

**Comment by singerj** [comment]
@AkankshaFarswan 

Sorry, one fix did not make it into the last commit. I made the necessary changes.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
Thank you.

Regards,
Akanksha Farswan

**Comment by AkankshaFarswan** [comment]
Hi,
This pipeline downloads 6 test datasets and runs the analysis on them. What
if we want to perform an analysis on a single dataset. Where in the program
should I make the changes ?
I tried to modify the file "SRP051153_run_info.txt" so that only 2 datasets
are downloaded. Do I need to make any changes in the code of
"run_analysis_locally" ?

**Comment by singerj** [comment]
Hi,

The 6 samples belong to 3 different patients. Since the overall goal is to extract somatic mutations you have to analyse a test and a control sample jointly. If you want the example to run only on one patient you can do so be removing certain lines from the "sample_mapping.tsv" in the examples directory. For example, if you want to analyse only patient one just keep the first two lines, which encode patient/experiment 1.

I hope that helps.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
Thank you for the help.
I have again encountered a problem in "run_analysis_locally" file. Please
see the screenshot below.

**Comment by singerj** [comment]
@AkankshaFarswan 

Hi, 

There is no screenshot.

Best,
Jochen

**Comment by singerj** [comment]
Unfortunately there is no image, please report the error message as text.

Best,
Jochen

**Comment by AkankshaFarswan** [comment]
Hi,

For this rule "rule picards_fix_mate_pair_and_sort:" , I am getting the
message below--

*Error in job picards_fix_mate_pair_and_sort while creating output file
out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam.*
*RuleException:*
*CalledProcessError in line 74 of
/home/Akanksha2/Documents/NGS-pipe/snake/common/bam_mod/bam_mod_snake.py:*
*Command 'picard -Xmx10G  FixMateInformation
INPUT=out/bwa/PCL-019/PAIREDEND/SRR1713652.bam
OUTPUT=out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam
SORT_ORDER=coordinate ASSUME_SORTED=false MAX_RECORDS_IN_RAM=500000
TMP_DIR=tmp/ 2> out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam.log'
returned non-zero exit status 1*
*  File
"/home/Akanksha2/Documents/NGS-pipe/snake/common/bam_mod/bam_mod_snake.py",
line 74, in __rule_picards_fix_mate_pair_and_sort*
*  File
"/home/Akanksha2/anaconda3/envs/ngs-pipe-dna/lib/python3.5/concurrent/futures/thread.py",
line 55, in run*

Please help.

Regards,
Akanksha

**Comment by AkankshaFarswan** [comment]
Hi,

I am not able to resolve the issue created by the rule "rule
picards_fix_mate_pair_and_sort:". I am getting the message below-->

*Error in job picards_fix_mate_pair_and_sort while creating output file
out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam.*
*RuleException:*
*CalledProcessError in line 74 of
/home/Akanksha2/Documents/NGS-pipe/snake/common/bam_mod/bam_mod_snake.py:*
*Command 'picard -Xmx10G  FixMateInformation
INPUT=out/bwa/PCL-019/PAIREDEND/SRR1713652.bam
OUTPUT=out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam
SORT_ORDER=coordinate ASSUME_SORTED=false MAX_RECORDS_IN_RAM=500000
TMP_DIR=tmp/ 2> out/fix_sorted/PCL-019/PAIREDEND/SRR1713652.bam.log'
returned non-zero exit status 1*
*  File
"/home/Akanksha2/Documents/NGS-pipe/snake/common/bam_mod/bam_mod_snake.py",
line 74, in __rule_picards_fix_mate_pair_and_sort*
*  File
"/home/Akanksha2/anaconda3/envs/ngs-pipe-dna/lib/python3.5/concurrent/futures/thread.py",
line 55, in run*

Please help.

Regards,
Akanksha
